---
title: "CV"
---

# Education

**PhD Candidate – Biosystems and Biodiversity** (January 2022 – Present)

University of Lethbridge \| Lethbridge, AB, Canada

- Thesis: Linking the population dynamics of rare species with small- and large-scale environmental drivers

- Supervisor: Dr. Jenny McCune

**Master of Science – Biology** (2018)

Arizona State University \| Tempe, AZ, USA

- Thesis: Nematode Herbivory as a Mechanism Behind the Influence of Precipitation on the Division of Net Primary Production between Above and Belowground Components

<!-- -->

- Supervisor: Dr. Osvaldo Sala

**Bachelor of Arts – Biology** (2016)

Bryn Mawr College \| Bryn Mawr, PA, USA

- Senior thesis: “The Effect of Introduced Species on Native Species in Morris Woods”

# Relevant Training

**Bayesian Integrated Population Modelling (IPM) using JAGS** (2024)

Institute for Mediterranean Studies \| Esporles, Spain

- Attended a week-long workshop on Bayesian population modelling, learning the basics of Bayesian statistics and gaining skills coding in JAGS

# Research Experience

**Biological Scientist II** (2019 – 2021)

University of Florida \| Davie, FL, USA

- Conducted field- and lab-work for soil nutrient analyses, including measuring soil pH, soil organic matter, and soil carbon and nitrogen, to better understand the effects of cattle grazing on agricultural soils

<!-- -->

- Organized lab data files, soil samples, and lab equipment to ensure lab activities ran efficiently

- Contributed to the extension program by assisting with logistics of workshops for community members on sustainable urban agriculture, including managing workshop enrollment and organizing local site visits

# Teaching Experience

**Teaching Assistant** (January 2022 – April 2026)\
Department of Biological Sciences - University of Lethbridge \| Lethbridge, AB, Canada

- BIOL 2150 – Biostatistics (Fall 2022, Fall 2023, Fall 2024, Fall 2025, Spring 2026)

- Taught a lab section with 24 students, introducing them to the statistical language R and the application of statistical tests with real datasets (each fall)

- Wrote improvements for the lab handbook and found four new datasets for labs to replace material that did not appropriately fit the statistical tests (spring 2026)

- BIOL 1020 – Diversity of Life Spring 2022, Fall 2025

- Taught lab sections with 24 students, introducing them to general lab concepts including microscope use as well as improving their understanding of biodiversity (spring 2022)

- Graded lecture quizzes each week for the 80 students in the course (fall 2025)

- BIOL 5850 – Advanced Statistics Using R (Spring 2025)

  - Graded weekly assignments for a graduate-level statistics course, providing feedback so students could better understand R and statistics

  - Attended lectures, contributing knowledge of R and statistics as needed

- BIOL 3300 – Evolution (Spring 2023, Spring 2024, Spring 2025)

- Taught lab sections with 24 students, presenting material related to computer simulations for students to understand evolutionary processes (spring 2023)

- Coordinated three lab sections, ensuring consistent grading among teaching assistants, entering grades, and updating previous worksheets as needed to better fit the material covered (Spring 2024)

- Graded exams for the lecture, including providing feedback on the three exams (spring 2025)

- BIOL 3170 – Population Biology (Fall 2023, Fall 2024)

  - Graded exams, student presentations, and group papers for about 70 students, including providing feedback on ways to improve writing and presentation skills

- BIOL 2001 – Research Internship I: Scientific Discovery (Spring 2024)

  - Graded project reports and research presentations for the eight students in conducting independent studies, providing feedback on each draft of the report to improve their writing skills

**Teaching Assistant**\
School of Life Sciences - Arizona State University \| Tempe, AZ, USA 

- BIO 282 – Conceptual Approaches to Biology for Majors II (Spring 2017, Fall 2017, Spring 2018)

  - Taught review/recitation section for an introductory biology course on ecology, reviewing lecture material with about 50 students, and helped write worksheets each week to develop student understanding of lecture material (Fall 2017-Spring 2018)

  - Taught labs for an introductory biology course, teaching basic biological lab techniques and experimental design (Spring 2017)

- BIO 181 – General Biology I: From Atoms to Organisms (Fall 2016)

  - Taught labs for an introductory biology course, with 24 students in each lab section gaining skills in basic biological lab techniques

# Related Professional Experience

**Temporary Field Technician** (2019)\
National Ecological Observatory Network \| Front Royal, VA, USA 

- Collected data on plant and forest characteristics including: tree phenology, plant biomass, plant species diversity, and leaf litter, contributing to a national open-access database of ecological data

**Intern, Directorate Fellows Program** (2015)

US Fish and Wildlife Service \| Springfield, MA, USA

- Conducted outreach for the Silvio O. Conte National Fish and Wildlife Refuge, participating in events promoting conservation and awareness of wildlife at a local science museum

- Developed plans for pollinator gardens at local schools, to increase community awareness of conservation

**Research Assistant** (2014)

University College Cork \| Cork, Ireland

- Contributed to field and lab work on a graduate student project about effects of sea level rise on populations of seagrass, helping with field surveys to map the location of populations and collect biomass samples for lab analysis, as well as working on lab work including processing dry biomass samples

**Research Assistant** (2013)

University of Missouri St. Louis \| Puerto Ayora, Galapagos, Ecuador

- Participated in fieldwork for a graduate student project on avian malaria, including netting birds and taking morphological measurements, as well as participating in mosquito population surveys

- Participated in a census of juvenile Galapagos hawks, contributing to a long-term demographic dataset

# Publications

**Wiedenfeld, Amy E.,** Yuxi Guo, Bei Huang, Hui Zhao, and Jiangxiao Qiu (2026). A meta-analysis to disentangle the effects of land management on soil denitrification. *Environmental Nexus*. 1(1). 10.1016/j.enex.2026.100006

# Work in Progress

**Wiedenfeld, Amy E.**, D. Ryan Norris, Axel Moehrenschlager, Courtlynd Cherpin, and J. L. McCune (submitted). Environmental drivers at the local and landscape scale influence the demographics of two plant species at risk.

# Community Involvement

**Science Fair Judge** (2023-2026)\
Lethbridge Regional Science Fair \| Lethbridge, AB, Canada 

- Judged science fair projects each year at the regional science fair with participants from 1st – 12th grade, assessing grade-level appropriate use of the scientific method

**Student Event Organizer** (2024-2025)

University of Lethbridge \| Lethbridge, AB, Canada

- Student organizer and moderator for the Graduate Student Symposium in the Department of Biological Sciences each January

- Organized contributed talks and schedule, as well as set up event and moderated one session

**Conference Abstract Reviewer** (2021-2023)

Ecological Society of America \| USA

- Reviewed 50 – 60 abstracts prior to their acceptance for the annual conference, rating abstracts on merit for conference presentation (April-May each year)

**Event Volunteer** (2017)

Asombro Institute \| Las Cruces, NM, USA

- Volunteer at one-day Butterfly Flutterby event, providing information on local wildlife to elementary school students to encourage engagement with the outdoors

# Professional Memberships

**Ecological Society of America,** Member August 2018 – Present

**Canadian Society for Ecology and Evolution**, Member February 2024 – Present

**Canadian Botanical Association,** Member, March 2025 – Present

- Served on the Board of Directors as a Student Director for the 2025-2027 term
